---
metrics:
  port: 9010 # port for prometheus metrics, served on /metrics and /

port: 3000 # port for RPC gateway

randomizeProviders: true # randomize the order of providers at startup for all proxies

proxies:
  - path: "eth" # directory path for the proxy (e.g. http://localhost:3000/eth)
    timeout: "1s" # timeout for both upstream requests and health checks
    healthChecks:
      interval: "10s" # how often to do healthchecks
      blockDiffThreshold: 2 # maximum allowed block difference between providers
    targets: # the order here determines the failover order
      - name: "meow"
        connection:
          http:
            url: "https://eth.meowrpc.com"
            # compression: true # Specify if the target supports request compression
      - name: "1rpc"
        connection:
          http:
            url: "https://1rpc.io/eth"
      - name: "Ankr"
        connection:
          http:
            url: "https://rpc.ankr.com/eth"
      - name: "publicnode"
        connection:
          http:
            url: "https://ethereum.publicnode.com"

  - path: "pol" # another proxy example
    timeout: "0.1s"
    healthChecks:
      interval: "8s"
      blockDiffThreshold: 2
    targets:
      - name: "polygon-rpc"
        connection:
          http:
            url: "https://polygon-rpc.com"
      - name: "nodies"
        connection:
          http:
            url: "https://polygon-pokt.nodies.app"

  - path: "sol"
    chainType: "solana"
    timeout: "1s"
    healthChecks:
      interval: "10s"
      blockDiffThreshold: 2
    targets:
      - name: "solana_mainnet"
        connection:
          http:
            url: "https://api.mainnet-beta.solana.com"
      - name: "publicnode"
        connection:
          http:
            url: "https://solana-rpc.publicnode.com"
